import type { MapProjection, MapViewBox } from './mapgeo';
import type { MapSpawn, Vec3 } from './types';

/**
 * Per-map data generated by scripts/generate_map_data.py from public sources:
 *   - sp-tarkov/server-csharp    PMC spawn points (with coordinates), extracts
 *   - the-hideout/tarkov-dev     projection config and positioned street labels
 *   - assets.tarkov.dev          the map SVG
 *
 * This is what keeps the app usable when the tarkov.dev API is down. Objective
 * zones, extract positions and switch positions are not in any public source,
 * so those still require the API.
 */
export interface MapSpawnPoint {
  id: string;
  zoneName: string | null;
  infiltration: string | null;
  position: Vec3;
}

export interface MapExtractInfo {
  name: string | null;
  entryPoints: string[];
  side: string | null;
  requirement: string | null;
  requirementTip: string | null;
  exfiltrationTime: number | null;
  chance: number | null;
}

export interface MapLabel {
  text: string;
  x: number;
  z: number;
}

export interface MapData {
  normalizedName: string;
  /** Sniper scav positions derived from the game's marksman waves. */
  sniperSpawns?: { zoneName: string | null; position: Vec3 }[];
  wikiName: string;
  svg: string;
  viewBox: MapViewBox;
  projection: MapProjection;
  spawnAccuracy: number;
  spawns: MapSpawnPoint[];
  extracts: MapExtractInfo[];
  labels: MapLabel[];
}

export interface MapIndexEntry {
  normalizedName: string;
  wikiName: string;
  spawns: number;
  extracts: number;
  labels: number;
  spawnAccuracy: number;
}

const cache = new Map<string, MapData>();
let indexCache: MapIndexEntry[] | null = null;

export async function fetchMapIndex(): Promise<MapIndexEntry[]> {
  if (indexCache) return indexCache;
  const response = await fetch('/data/maps-index.json');
  if (!response.ok) throw new Error(`Could not load the map list (${response.status})`);
  indexCache = (await response.json()) as MapIndexEntry[];
  return indexCache;
}

export async function fetchMapData(normalizedName: string): Promise<MapData> {
  const cached = cache.get(normalizedName);
  if (cached) return cached;

  const response = await fetch(`/data/${normalizedName}.json`);
  if (!response.ok) throw new Error(`Could not load data for ${normalizedName} (${response.status})`);
  const data = (await response.json()) as MapData;
  cache.set(normalizedName, data);
  return data;
}

/** Present offline spawns in the shape the rest of the app consumes. */
export function toMapSpawns(spawns: MapSpawnPoint[]): MapSpawn[] {
  return spawns.map((spawn) => ({
    zoneName: spawn.zoneName,
    position: spawn.position,
    sides: ['Pmc'],
    categories: ['Player'],
  }));
}

/** Group spawn points by infiltration zone, which is what players recognise. */
export function spawnZones(spawns: MapSpawnPoint[]): { infiltration: string; spawns: MapSpawnPoint[] }[] {
  const groups = new Map<string, MapSpawnPoint[]>();
  for (const spawn of spawns) {
    const key = spawn.infiltration ?? spawn.zoneName ?? 'Unknown';
    const list = groups.get(key);
    if (list) list.push(spawn);
    else groups.set(key, [spawn]);
  }
  return Array.from(groups, ([infiltration, group]) => ({ infiltration, spawns: group }))
    .sort((a, b) => a.infiltration.localeCompare(b.infiltration));
}

/**
 * Why an extract is not a plain PMC exit. `null` means it is a normal one you
 * can walk out of with any kit.
 */
export function extractRestriction(extract: MapExtractInfo): string | null {
  if (extract.side === 'Scav') return 'scav only';
  if (extract.side === 'Coop') return 'needs a co-op scav';

  switch (extract.requirement) {
    case 'Empty': return 'no backpack';
    case 'ScavCooperation': return 'needs a co-op scav';
    case 'TransferItem': return 'hand over an item';
    case 'Reference': return 'needs Red Rebel';
    case 'Train': return 'train only';
    case 'WorldEvent': return 'needs a switch or event';
    default: return null;
  }
}

/** Plain PMC exits: no scav route, no special kit or condition. */
export function isPlainPmcExtract(extract: MapExtractInfo): boolean {
  return extractRestriction(extract) === null;
}

/** Extracts reachable from a given infiltration zone. */
export function extractsForSpawn(extracts: MapExtractInfo[], infiltration: string | null): MapExtractInfo[] {
  if (!infiltration) return extracts;
  return extracts.filter((e) => e.entryPoints.length === 0 || e.entryPoints.includes(infiltration));
}

/**
 * SPT ships untranslated extract ids ("EXFIL_ZB013", "customs_sniper_exit"),
 * which are not what the game shows on the exit timer. The API's translated
 * name is preferred; this is the readable fallback for when it is unavailable.
 */
export function extractDisplayName(rawName: string): string {
  const stripped = rawName.replace(/^exfil[_\s-]*/i, '').replace(/_/g, ' ').trim();
  if (!stripped) return rawName;
  return stripped
    .split(/\s+/)
    // Leave anything with its own capitals or digits alone: "ZB-1011", "V-Ex".
    .map((word) => (/[A-Z0-9]/.test(word) ? word : word[0].toUpperCase() + word.slice(1)))
    .join(' ');
}
