import type { Vec3 } from './types';

/**
 * Projection for one map, generated by scripts/generate_map_data.py from
 * tarkov.dev's own Leaflet config.
 *
 * Their chain, for a game point (x, z) with rotation r and transform [a,b,c,d]:
 *   x' = x*cos(r) - z*sin(r)
 *   y' = x*sin(r) + z*cos(r)
 *   px = a*x' + b
 *   py = -c*y' + d        (Leaflet's scaleY is transform[2] * -1)
 *
 * The SVG is stretched across the pixel rect of the two bounds corners, so
 * normalising against `rect` gives a position inside the viewBox.
 *
 * The generator verifies each map by checking that its real spawn points land
 * inside the image; every shipped map scores at least 94%.
 */
export interface MapProjection {
  transform: [number, number, number, number];
  rotation: number;
  rect: { xMin: number; xMax: number; yMin: number; yMax: number };
}

export interface MapViewBox {
  width: number;
  height: number;
}

function toPixels(x: number, z: number, projection: MapProjection): { px: number; py: number } {
  const [a, b, c, d] = projection.transform;
  const radians = (projection.rotation * Math.PI) / 180;
  const cos = Math.cos(radians);
  const sin = Math.sin(radians);
  return {
    px: a * (x * cos - z * sin) + b,
    py: -c * (x * sin + z * cos) + d,
  };
}

/** Game-world position -> point inside the map's SVG viewBox. */
export function gameToSvg(p: Vec3, projection: MapProjection, viewBox: MapViewBox): { x: number; y: number } {
  const { px, py } = toPixels(p.x, p.z, projection);
  const { xMin, xMax, yMin, yMax } = projection.rect;
  return {
    x: ((px - xMin) / (xMax - xMin)) * viewBox.width,
    y: ((py - yMin) / (yMax - yMin)) * viewBox.height,
  };
}

/** Inverse of gameToSvg: a point clicked on the map -> game coordinates. */
export function svgToGame(
  point: { x: number; y: number },
  projection: MapProjection,
  viewBox: MapViewBox,
): Vec3 {
  const { xMin, xMax, yMin, yMax } = projection.rect;
  const px = xMin + (point.x / viewBox.width) * (xMax - xMin);
  const py = yMin + (point.y / viewBox.height) * (yMax - yMin);

  const [a, b, c, d] = projection.transform;
  const rotatedX = (px - b) / a;
  const rotatedY = (d - py) / c;

  const radians = (projection.rotation * Math.PI) / 180;
  const cos = Math.cos(radians);
  const sin = Math.sin(radians);

  // Undo the rotation: the forward pass is a standard 2D rotation of (x, z).
  return {
    x: rotatedX * cos + rotatedY * sin,
    y: 0,
    z: -rotatedX * sin + rotatedY * cos,
  };
}

/** Straight-line distance in game metres, ignoring elevation. */
export function distance2d(a: Vec3, b: Vec3): number {
  return Math.hypot(a.x - b.x, a.z - b.z);
}

/**
 * Shortest distance from a point to a path, in game metres.
 *
 * Measured against the segments rather than the stops, because "on the way"
 * means beside the line you walk, not near a corner of it.
 */
export function distanceToPath(point: Vec3, path: Vec3[]): number {
  if (path.length === 0) return Infinity;
  if (path.length === 1) return distance2d(point, path[0]);

  let best = Infinity;
  for (let i = 0; i < path.length - 1; i++) {
    best = Math.min(best, distanceToSegment(point, path[i], path[i + 1]));
  }
  return best;
}

function distanceToSegment(point: Vec3, from: Vec3, to: Vec3): number {
  const dx = to.x - from.x;
  const dz = to.z - from.z;
  const lengthSquared = dx * dx + dz * dz;
  if (lengthSquared === 0) return distance2d(point, from);

  // How far along the segment the closest point lies, clamped to its ends.
  const t = Math.max(0, Math.min(1,
    ((point.x - from.x) * dx + (point.z - from.z) * dz) / lengthSquared));

  return Math.hypot(point.x - (from.x + t * dx), point.z - (from.z + t * dz));
}
